### ISSUE TITLE
Add engine mode 4

### ISSUE THREAD

**Issue by Mrgaton** [DrexHD/AntiXray#42]
The engine mode 4 is just to replace everything with one block like stone so it appears to be absolutely nothing

**Comment by DrexHD** [comment]
You are basically describing engine mode 1. The reason you can still see blocks in engine mode 1 is that ores next to air can't be replaced with stone, otherwise legit players wont be able to see exposed ores either. To hide all ores an approach like #16 is required, which is rather complicated and computationally expensive!
